### ISSUE TITLE
DenoiseSharpen feedback

### ISSUE THREAD

**Issue by nicholascarroll** [devernay/openfx-misc#44]
uploading the image I am using. it is taken with BlackMagic Production Camera 4K which is quite a noisy camera. The original DNG was converted to TIFF using 'dcraw -w -T'.
[A_1_2017-08-14_2206_C0001_003618.tiff.tar.gz](https://github.com/devernay/openfx-misc/files/430420/A_1_2017-08-14_2206_C0001_003618.tiff.tar.gz)

**Comment by nicholascarroll** [comment]
I am looking **only in the blue channel** (it has the most noise). First I tried DenoiseSharpen v.1.0 with default settings and clicking on *Analyze Noise Levels*. Cycling through each *Color Model* to find the best one. All produced a very slight denoise, but relatively quite blurry; the good ones were Y'CbCCr(A) and CIE L*a*b(A). The default *Channel Settings* are very low; I would suggest about five times that value. 

Sharpen helped with the hair but introduced a dark margin inside the edge of the shirt.

DenoiseSharpen v 1.0 seems about as good as dcraw's denoiser which is also wavelet based.

Not a bad denoiser and definitely worth having if there is no money to buy a high end denoiser.

**Comment by devernay** [comment]
did you re-run analyse after changing the color model? will add a hint about that in the doc.

noise analysis is based upon a Gaussian noise assumption. If there is speckle noise, I would suggest using Median or SmoothPatchBased.

It is basically the wavelet code of dcraw (which I had to understand and reverse-engineer), but with a better threshold choice, based on BayesShift.

I also added OpenMP support, so if you compile it with `-fopenmp`you get extra speed.

- `make [options] CXXFLAGS_ADD=-fopenmp LDFLAGS_ADD=-fopenmp` to compile
  with OpenMP support (available for CImg-based plugins and DenoiseSharpen).

It could be made edge-aware, as in https://jo.dreggn.org/home/2011_atrous.pdf but the algorithm to find the right paramaters may be too expensive for video.

**Comment by nicholascarroll** [comment]
Yes each time I changed the color model I did click analyze again.

**Comment by devernay** [comment]
I made large modifications to the plugin. It now analyses different spatial frequencies.

It seems to work quite well on your image:

- analyze noise on the whole image
- adjust the "noise level gain" slider (3.0 seems to give rather good results on this image, probably because the noise is not quite Gaussian)

**Comment by nicholascarroll** [comment]
When I compile this version on Linux it won't show up in Natron. First I tried `make CXXFLAGS_ADD=-fopenmp LDFLAGS_ADD=-fopenmp` then I tried simply 'make'. What could it be?

**Comment by olear** [comment]
Did you replace the existing Misc.ofx? And did you clear the plugin cache?

**Comment by nicholascarroll** [comment]
Thanks that did it.

**Comment by nicholascarroll** [comment]
I think this is a good foundation. Y'CbCr(A). Excellence is within reach.

**Comment by nicholascarroll** [comment]
Is adjusting the *Noise Levels* the same as adjusting the *Frequency* and *Correction* Amounts?

**Comment by devernay** [comment]
the per-frequency gains are multiplied by the Noise Level Gain and by the thresholds for this frequency to obtain the final threshold.

The amounts control how soft the thresholding is. Any value lower than 1 means to keep some noise.

I'll clarify this in the tooltips.

**Comment by nicholascarroll** [comment]
Can you please have less parameters? If the threshold is being modulated as an average of all the possible good options on a per pixel basis, what is there left for UI parameters to do?

If there is gaussian blur going on isn't that going to destroy alot of edge information and across scale?

**Comment by devernay** [comment]
- more doc: https://github.com/devernay/openfx-misc/commit/556e55d1ac980c9cb389d6d28575b8c9a44ebbfc
- per-channel gains, for completeness: https://github.com/devernay/openfx-misc/commit/c53d6c7dbd65adfe8bb3b4de73f3030371815a15
- mall fix for noise analysis (may not change much, but you may want to re-run your analysis): https://github.com/devernay/openfx-misc/commit/586d49855ac7a4654f593a795811825749abff62

**Comment by nicholascarroll** [comment]
Is it faster if you turn off channels and does that diminish the result?
The *Output* set to Noise is that working OK?

**Comment by devernay** [comment]
if you turn off one channel (by setting its gain to zero, it is not processed, so yes it's faster.

**Comment by nicholascarroll** [comment]
When I set output to Noise, it still shows much image. But gain is only set at 2. is that a defect?

**Comment by devernay** [comment]
if it shows that different areas have different noise, it's OK (especially because denoising is done in YCbCr which is gamma compressed)
if you see all the contours / textures, if may be denoising to much.
note that when there is a lot of noise, halos may appear around objects. The solution is to implement edge-aware denoising:
// - https://www.darktable.org/wp-content/uploads/2011/11/hdl11_talk.pdf <https://www.darktable.org/wp-content/uploads/2011/11/hdl11_talk.pdf>
// - https://jo.dreggn.org/home/2011_atrous.pdf <https://jo.dreggn.org/home/2011_atrous.pdf>

--
Frédéric Devernay, Research Scientist, INRIA
frederic.devernay@inria.fr

**Comment by nicholascarroll** [comment]
GO DARKTABLE!! 
Here is a second image for testing. This was shot with the Blackmagic URSA camera (DNG was converted to TIFF using 'dcraw -w -T): 
[Blackmagic URSA Mini_1_2016-07-20_0111_C0015_000432.tiff.tar.gz](https://github.com/devernay/openfx-misc/files/436043/Blackmagic.URSA.Mini_1_2016-07-20_0111_C0015_000432.tiff.tar.gz)

**Comment by devernay** [comment]
basic usage only has one button (analyze) and one parameter (noise level gain). All other parameters are for fine-tuning.

there is no Gaussian blur going on, it's all wavelets, and wavelets proceed at different scales/frequencies.

fred

**Comment by devernay** [comment]
I just fixed a bug in noise analysis and added a new setting ("B3 Spline interpolation"). Can you please test and report (analysis must be rerun).
It seems like I get good results with noisel level gain = 1.1 on your images

**Comment by nicholascarroll** [comment]
Edge avoidance is really going to be necessary because at a *Gain* that is good enough to get the fireflies out of the moving image, the edges are getting ruined, so it defeats the purpose. For the image of the shoe, a *Gain* of 1.1 is fine but when we have hair blowing about the *Gain* must be alot higher. I have some footage of hair blowing - 250 frames @50fps at 1GB in raw dng. Do you want that footage?

Anyway, testing where you are at now, I compiled the latest and ran but I can't really tell the difference to the previous version. I don't see any parameter called "B3 Spline interpolation". 

### Test results
The noise gain needs to be at 3.0. However this blurs edges. Sharpen brings back the hair which looks fine, but the halo is there on the inside of the body's sillhouette. 

In the first test plate with gain = 3.0 and sharpen = 4.0 the hair looks right:
![plate1_hair 2016-08-26 13-10-27](https://cloud.githubusercontent.com/assets/1062708/17993062/064bbb6e-6b90-11e6-99a0-9717572cca16.png)

however the halo is there on the leg and that ruins the edge for keying:
![plate1_leg 2016-08-26 13-11-22](https://cloud.githubusercontent.com/assets/1062708/17993104/5e60a602-6b90-11e6-83d2-a3d4d13b5942.png)

In the second test plate with gain = 3.0 and no sharpening, look at the heel of the shoe and the other edges. You can see the halo there.
![plate2 2016-08-26 13-14-38](https://cloud.githubusercontent.com/assets/1062708/17993132/98201d46-6b90-11e6-9b84-1869e1d610c5.png)


### Test Steps
On the image of the man (A_1_2017-08-14_2206_C0001_003618.tiff) I am doing this:
1. Add the DenoiseSharpen node to the read
2. Run *Analyze Noise Levels*
3. Raise gain until noise is acceptable. 
4. Raise Sharpen Amount
I am not going further than this into tuning at this stage because edge avoidance is going to be the biggest improvement.

**Comment by devernay** [comment]
If you don't have the "B3 Spline Interpolation" parameter, then you **still have the analysis bug** which was fixed in https://github.com/devernay/openfx-misc/commit/8cffa3068e3f578e415a17e394a184f014807b32 and the B3 parameter was introduced in
https://github.com/devernay/openfx-misc/commit/8a210869c75b4b853d0574df6fe12dd4564f543c
You should **pull and recompile**, then re-test.

You should not have to bring the gain up to 3.

Sharpen should either be used to test for the presence of noise while tuning parameters (, or for aesthetic purposes, but not before a keyer.
See the documentation I wrote ("?" button) and the video tutorials for the NukeX denoise plugin (although the parameters are not the same, and the algorithm may be different).
https://www.youtube.com/watch?v=4GdVKwVKF8k
https://www.youtube.com/watch?v=h75OUvQcUFc

As for the halo, around the leg, it is already present in the noisy image. Denoising will not remove it. The signal itself is seriously damaged in the raw image. 

There are also overshoots in the blue channel on the left and right side of the shirt: you will see that odd colums are darker at the edge. This is either from the camera or from dcraw.

Edge advoiding wavelets will be there soon, but don't expect too much from it. Denoising cannot cure all defects present in the raw footage, just noise.

**Comment by devernay** [comment]
another bug fixed in https://github.com/devernay/openfx-misc/commit/efea1c73da50c9793073e03772d38a6866f57432 for B3

**Comment by nicholascarroll** [comment]
OK I got the B3 param in now. testing and will update in a few minutes.
Don't overlook this: https://github.com/devernay/openfx-misc/files/439207/hair.mp4.zip

**Comment by devernay** [comment]
You were using gain = 3.0 on that video, which is way too high

**Comment by nicholascarroll** [comment]
B3 spline is subtle and once the result goes through the keyer the edges are blurred more and have more halo with B3 spline. That is on the image of the shoe and also one of hair (not uploaded). Here's a couple shots. 
![hair](https://cloud.githubusercontent.com/assets/1062708/18007869/1a6f14b6-6be9-11e6-8d1a-0c2c1196090b.png)
![shoe ](https://cloud.githubusercontent.com/assets/1062708/18007881/26e49a5e-6be9-11e6-9fe8-f8cb2323456f.png)

**Comment by nicholascarroll** [comment]
> You were using gain = 3.0 on that video, which is way too high

Just for the matte Fred. In the moving image RGB even though there is still noise at say 1.0 you don't notice it. But pull a matte off that and your alpha will show up the noise alot and it won't match. Especially in the moving image. So for they key it needs to be very high, for the edges and soft mattes.

**Comment by nicholascarroll** [comment]
Or perhaps I should say, *higher* , like 2.0, not *very high* like 3.0.

**Comment by devernay** [comment]
2.0 seems high too. Keep it at 1.0 for all your tests, anything above that *will* smooth the signal.
Be careful not to mistake noise with background texture, which is not noise. For example the dirt on the ground, the wires, the folds and shadows should still be there after denoising, because it's in the signal. Same for the motion blur. All these should be taken care of by the Keyer or by other processes (garbage matte, wire and dirt removal)

**Comment by nicholascarroll** [comment]
> Be careful not to mistake noise with background texture, which is not noise.

I think if its moving around like insects its noise. Even with a garbage matte, the garbage matte has to end somewhere, and so it contrasts against the noisy foreground, giving a sparkle, petiller, where the garbage ends and the edge begins.

What would be great in denoise for matte pulling purposes, is control of the falloff / rolloff. What do you think?

**Comment by nicholascarroll** [comment]
I'll do some more tests especially with semitransparent and motion blur.

**Comment by nicholascarroll** [comment]
Semitransparent and motion blur work fine even at high levels of denoise. So its only edges that are a concern. Now I will go back to single frames and compare DenoiseSharpen at *Gain* = 1.0 versus the different options available in Darktable.

**Comment by nicholascarroll** [comment]
A couple of possible enhancements to consider:
1. Maybe set Lock Noise Analysis = true automatically when Analyze completes?
2. If you are averaging by all eight neighbouring pixels, can you also include the two pixels previous/next frame?

**Comment by nicholascarroll** [comment]
I used a photo from Canon 5D Mark II ISO 1000 to compare DenoiseSharpen to the Darktable modules 'raw denoise' and 'profiled denoise'. DenoiseSharpen is significantly better than 'raw denoise' and about as good as 'profiled denoise'. 

That's pretty good work, well done.

**Comment by nicholascarroll** [comment]
I used footage from Canon 5D Mark II ISO 1000 to compare DenoiseSharpen to the Darktable modules 'raw denoise' and 'profiled denoise'. DenoiseSharpen without any sharpen comes out equivalent to 'raw denoise'.

**Comment by devernay** [comment]
> A couple of possible enhancements to consider:
> 1. Maybe set Lock Noise Analysis = true automatically when Analyze completes?
> 
good suggestion
> 2. If you are averaging by all eight neighbouring pixels, can you also include the two pixels previous/next frame?
> 

it's not averaging, it's computing wavelets, and wavelets in the time dimension are known to be not reliable, unless they are "guided" by the optical flow (the optical flow between two frames can be several dozen pixels.

**Comment by nicholascarroll** [comment]
going to test this shortly on hair on lowlight greenscreen footage from Blackmagic URSA raw dng.

**Comment by nicholascarroll** [comment]
WOW!

**Comment by nicholascarroll** [comment]
[DENOISE-TEST-DEFAULTS.mp4.zip](https://github.com/devernay/openfx-misc/files/472077/DENOISE-TEST-DEFAULTS.mp4.zip)

**Comment by nicholascarroll** [comment]
In that test B3 is giving a better result. It is giving more solid hair strands which is good. But it is very subtle. 

For pulling mattes this denoiser is absolutely first class. Well done Fred!

I will do more testing in the next few days and update again.

**Comment by nicholascarroll** [comment]
On this test footage am not seeing a difference between the adaptive radius values (apart from zero).

**Comment by devernay** [comment]
you have to look close to the edges to see differences with the adaptive radius.
what do you call "normal images" ? Edge avoidance is probably not the holy grail you are waiting for.

**Comment by nicholascarroll** [comment]
normal meaning not greenscreen. 

Will add more feedback in a couple days.

**Comment by devernay** [comment]
do you get a halo effect with non-greenscreen images? subtract original image from denoised to check.

**Comment by nicholascarroll** [comment]
feedback

1. I'm not seeing halo (but I am not sure I am doing it right).

2. I suggest removing the sharpen controls because (a) it degrades the image, (b) there are different sharpen algorithms and (c) it can just as easily be applied downstream.

3. the B spline and the adaptive radius are good as parameters, just as you have them.

4. Maybe move the less commonly used parameters into an 'Advanced' region.

5. Yes I do think edge awareness is the missing ingredient:  the output mode 'Noise', actually looks like an edge detector: therefore there is room for improvement.

**Comment by devernay** [comment]
> 
> I suggest removing the sharpen controls because (a) it degrades the image, (b) there are different sharpen algorithms and (c) it can just as easily be applied downstream.
> 
> 
sorry, I won't apply this suggestion:

this is wavelet-based denoising and sharpening, and either:
- you want sharpen without denoising, in this case it can be used without denoising, using this plugin
- you want to sharpen after denoising, and in this cas it is much better to do it at the same stage. The result is different if you do it afterwards

I know there are other sharpening algorithms (and wavelet-based sharpening is known to be one of the best ones around), and I know there are also other denoising algorithms.
However, if you want to apply both wavelet-based denoising and wavelet-based sharpening, you have to do it using the same wavelet decomposition.

> the B spline and the adaptive radius are good as parameters, just as you have them.
> 
> Maybe move the less commonly used parameters into an 'Advanced' region.
> 
> 
In fact, we consider every single parameter which is inside a foldable group as an advanced parameter. Most users will just analyze the noise and adjust the global gain.

> Yes I do think edge awareness is the missing ingredient: the output mode 'Noise', actually looks like an edge detector: therefore there is room for improvement.
> 
> 
When the gain is 1, or is a reasonable value (max 1.5), I seriously doubt you see that in the noise, because very little noise is removed around the edges. You probably see different amounts of noise removed from different regions, and this is normal.

Sorry, but I won't spend more time on this for the time being, unless someone pays big money for it. Feel free to ditch this one and use DE:Noise, NeatVideo, or any other commercial alternative (and no, they are not expensive for what they are - consider the time I spent on this one)

**Comment by nicholascarroll** [comment]
Really good work @devernay. It is definitely very useful to have bundled in Natron.
