### ISSUE TITLE
Is the "presets" folder supposed to be included in packages?

### ISSUE THREAD

**Issue by z3ntu** [devernay/openfx-misc#45]
Hello, I am the maintainer of the Arch Linux package for [openfx-misc](https://aur.archlinux.org/packages/openfx-misc/).
I noticed that the size of the package went up 33MB from version 2.1.9 (14,72 MiB) to 2.2.0 (48,27 MiB). The main size difference I found was because there is a folder called `/usr/OFX/Plugins/Shadertoy.ofx.bundle/Contents/Resources/presets/` which has 33 MB of videos and pictures in it. Is this folder supposed to be included in the distribution packages?

**Comment by devernay** [comment]
Yes, but it could be distributed in a separate package. Actually, shader toy itself could be in a separate package.Le 18 janv. 2017 10:16 PM, Luca Weiss <notifications@github.com> a écrit :Hello, I am the maintainer of the Arch package for openfx-misc.
I noticed that the size of the package went up 33MB from version 2.1.9 (14,72 MiB) to 2.2.0 (48,27 MiB). The main size difference I found was because there is a folder called /usr/OFX/Plugins/Shadertoy.ofx.bundle/Contents/Resources/presets/ which has 33 MB of videos and pictures in it. Is this folder supposed to be included in the distribution packages?

**Comment by z3ntu** [comment]
It's not worth splitting the packages for the AUR. Thanks for the info!

**Comment by devernay** [comment]
Note that Shadertoy works without the images/videos. They are here to be able to reproduce the behavior of the real shadertoy https://www.shadertoy.com/
Also note that the images are downloaded during the build (as is CImg.h). This may be an issue if your build platform is isolated from the WAN.

**Comment by devernay** [comment]
BTW, if someone needs help packaging Natron properly, I can help (OpenColorio-configs deserve a separate package for example, since they may be used from other apps)

**Comment by z3ntu** [comment]
[natron_openfx_files.txt](https://github.com/devernay/openfx-misc/files/715908/natron_openfx_files.txt)
These are the files currently packaged in natron, openfx-arena, openfx-io & openfx-misc.
